config/routes.rb
Rails.application.routes.draw do
  resources :rues
  root :to => "rues#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rue.rb
class Rue < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rues_controller.rb
class RuesController < ApplicationController
  before_action :set_rue, only: [:show, :edit, :update, :destroy]

  # GET /rues
  # GET /rues.json
  def index
    @rues = Rue.all
  end

  # GET /rues/1
  # GET /rues/1.json
  def show
  end

  # GET /rues/new
  def new
    @rue = Rue.new
  end

  # GET /rues/1/edit
  def edit
  end

  # POST /rues
  # POST /rues.json
  def create
    @rue = Rue.new(rue_params)

    respond_to do |format|
      if @rue.save
        format.html { redirect_to @rue, notice: 'Rue was successfully created.' }
        format.json { render :show, status: :created, location: @rue }
      else
        format.html { render :new }
        format.json { render json: @rue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rues/1
  # PATCH/PUT /rues/1.json
  def update
    respond_to do |format|
      if @rue.update(rue_params)
        format.html { redirect_to @rue, notice: 'Rue was successfully updated.' }
        format.json { render :show, status: :ok, location: @rue }
      else
        format.html { render :edit }
        format.json { render json: @rue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rues/1
  # DELETE /rues/1.json
  def destroy
    @rue.destroy
    respond_to do |format|
      format.html { redirect_to rues_url, notice: 'Rue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rue
      @rue = Rue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rue_params
      params.require(:rue).permit(:rue, :histoire)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rues_helper.rb
module RuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruesdebordeaux</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rues/_form.html.erb
<%= form_for(rue) do |f| %>
  <% if rue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rue.errors.count, "error") %> prohibited this rue from being saved:</h2>

      <ul>
      <% rue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rue %>
    <%= f.text_field :rue %>
  </div>

  <div class="field">
    <%= f.label :histoire %>
    <%= f.text_area :histoire %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rues/edit.html.erb
<h1>Editing Rue</h1>

<%= render 'form', rue: @rue %>

<%= link_to 'Show', @rue %> |
<%= link_to 'Back', rues_path %>

app/views/rues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rues</h1>

<table>
  <thead>
    <tr>
      <th>Rue</th>
      <th>Histoire</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rues.each do |rue| %>
      <tr>
        <td><%= rue.rue %></td>
        <td><%= rue.histoire %></td>
        <td><%= link_to 'Show', rue %></td>
        <td><%= link_to 'Edit', edit_rue_path(rue) %></td>
        <td><%= link_to 'Destroy', rue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rue', new_rue_path %>

app/views/rues/new.html.erb
<h1>New Rue</h1>

<%= render 'form', rue: @rue %>

<%= link_to 'Back', rues_path %>

app/views/rues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rue:</strong>
  <%= @rue.rue %>
</p>

<p>
  <strong>Histoire:</strong>
  <%= @rue.histoire %>
</p>

<%= link_to 'Edit', edit_rue_path(@rue) %> |
<%= link_to 'Back', rues_path %>